### ISSUE TITLE
Help on download

### ISSUE THREAD

**Issue by HaSerZin** [steveonly2/Radiance-Macro#2]
How can I download the macro? I can't find any file that was supposed to be a download (tell me if it's not released yet)

**Comment by curiouspengu** [comment]
[Release](https://github.com/steveonly2/Radiance-Macro/releases)

**Comment by HaSerZin** [comment]
Yeah, it just appears this (I'm on phone btw)
![Screenshot_20241231-063148-027](https://github.com/user-attachments/assets/17a81f78-5787-4777-88f4-41be8da4b1e1)

**Comment by curiouspengu** [comment]
Source code: zip
